name: pokeapi_functional
description: Functional Programming using fpdart. Fetch and display pokemon from pokeApi.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  freezed: ^2.3.2
  fpdart:
    path: ../../.
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.2.0
  build_runner: ^2.4.1
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.1

flutter:
  uses-material-design: true
