name: fpdart
description: >
  Functional programming in Dart and Flutter.
  All the main functional programming types and patterns fully documented, tested, and with examples.
version: 1.1.1
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
author: Maglione Sandro <lass.maglio@gmail.com>
documentation: https://www.sandromaglione.com/articles
issue_tracker: https://github.com/SandroMaglione/fpdart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  glados: ^1.1.6
  collection: ^1.17.2

screenshots:
  - description: "Basic usage of fpdart Option, Either, TaskEither types."
    path: example/screenshot_fpdart.png
